/** Types generated by quicktype.io */
export interface HolidayAPI {
	meta: Meta;
	response: Response;
}

interface Meta {
	code: number;
}

interface Response {
	holidays: Holiday[];
}

interface Holiday {
	name: string;
	description: string;
	country: Country;
	date: DateClass;
	type: string[];
	primary_type: string;
	canonical_url: string;
	urlid: string;
	locations: string;
	states: string;
}

interface Country {
	id: string;
	name: string;
}

interface DateClass {
	iso: string;
	datetime: Datetime;
	timezone?: Timezone;
}

interface Datetime {
	year: number;
	month: number;
	day: number;
	hour?: number;
	minute?: number;
	second?: number;
}

interface Timezone {
	offset: string;
	zoneabb: string;
	zoneoffset: number;
	zonedst: number;
	zonetotaloffset: number;
}
