import { Location } from "shared/geo";

/** 
 * --Types generated by quicktype.io--
 * More info in https://developers.google.com/maps/documentation/geocoding/requests-geocoding#GeocodingResponses
 */
export interface APIGeocode {
    readonly results: Result[];
    readonly status:  string;
}

export interface Result {
    readonly address_components: AddressComponent[];
    readonly formatted_address:  string;
    readonly geometry:           Geometry;
    readonly navigation_points:  NavigationPoint[];
    readonly place_id:           string;
    readonly plus_code:          PlusCode;
    readonly types:              string[];
}

export interface AddressComponent {
    readonly long_name:  string;
    readonly short_name: string;
    readonly types:      string[];
}

export interface Geometry {
    readonly location:      Location;
    readonly location_type: string;
    readonly viewport:      Viewport;
}

interface Viewport {
    readonly northeast: Location;
    readonly southwest: Location;
}

export interface NavigationPoint {
    readonly location: NavigationPointLocation;
}

export interface NavigationPointLocation {
    readonly latitude:  number;
    readonly longitude: number;
}

export interface PlusCode {
    readonly compound_code: string;
    readonly global_code:   string;
}