/**
 * Types generated by DeepSeek
 */
interface ImageDetails {
	filename: string;
	name: string;
	mime: string;
	extension: string;
	url: string;
}

interface ImageData {
	id: string;
	title: string;
	url_viewer: string;
	url: string;
	display_url: string;
	width: number;
	height: number;
	size: number;
	time: number;
	expiration: number;
	image: ImageDetails;
	thumb: ImageDetails;
	medium: ImageDetails;
	delete_url: string;
}

export interface UploadApiResponse {
	data: ImageData;
	success: boolean;
	status: number;
}
